# Generated by Django 5.2.5 on 2025-08-24 15:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3, primary_key=True, serialize=False, verbose_name='currency code')),
                ('conversion_rate_to_zar', models.DecimalField(decimal_places=4, help_text='Exchange rate from this currency to South African Rand', max_digits=10, verbose_name='conversion rate to ZAR')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate percentage for affiliate sales', max_digits=5, verbose_name='commission rate')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_affiliates', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_affiliates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'db_table': 'affiliates',
            },
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='commission amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.affiliate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Affiliate Commission',
                'verbose_name_plural': 'Affiliate Commissions',
                'db_table': 'affiliate_commissions',
            },
        ),
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('ip_geolocation', 'IP Geolocation'), ('velocity_check', 'Velocity Check'), ('card_verification', 'Card Verification'), ('behavioral_analysis', 'Behavioral Analysis'), ('blacklist_check', 'Blacklist Check')], max_length=30, verbose_name='fraud check type')),
                ('flag', models.BooleanField(default=False, help_text='Whether this check flagged the order as potentially fraudulent', verbose_name='flagged as suspicious')),
                ('details', models.TextField(help_text='Additional details about the fraud check results', verbose_name='check details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Fraud Log',
                'verbose_name_plural': 'Fraud Logs',
                'db_table': 'fraud_logs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('payfast', 'PayFast'), ('ozow', 'Ozow'), ('paygate', 'PayGate'), ('peach_payments', 'Peach Payments'), ('yoco', 'Yoco')], default='stripe', max_length=20, verbose_name='payment gateway')),
                ('transaction_id', models.CharField(help_text='Unique transaction ID from the payment gateway', max_length=255, unique=True, verbose_name='transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='payment amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='payout amount')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('payfast', 'PayFast'), ('ozow', 'Ozow'), ('paygate', 'PayGate'), ('peach_payments', 'Peach Payments'), ('yoco', 'Yoco')], default='stripe', max_length=20, verbose_name='payout gateway')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='payout status')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for the payout', max_digits=10, verbose_name='payout fee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'payouts',
            },
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='country code')),
                ('rate', models.DecimalField(decimal_places=2, help_text='VAT rate percentage', max_digits=5, verbose_name='VAT rate')),
                ('effective_from', models.DateField(help_text='Date when this VAT rate becomes effective', verbose_name='effective from')),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'db_table': 'vat_rates',
                'indexes': [models.Index(fields=['country', 'effective_from'], name='vat_rates_country_4db708_idx')],
                'unique_together': {('country', 'effective_from')},
            },
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['referrer'], name='affiliates_referre_eab4be_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['referred'], name='affiliates_referre_23d193_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliate',
            unique_together={('referrer', 'referred')},
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['affiliate'], name='affiliate_c_affilia_63b526_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['order'], name='affiliate_c_order_i_237c53_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['paid_at'], name='affiliate_c_paid_at_7a3b54_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['order'], name='fraud_logs_order_i_82caa0_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['check_type', 'flag'], name='fraud_logs_check_t_d5c77d_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['timestamp'], name='fraud_logs_timesta_7ededf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_order_i_b32b33_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payments_gateway_3ac0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['user', 'status'], name='payouts_user_id_ed1681_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['gateway'], name='payouts_gateway_651a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['created_at'], name='payouts_created_1441ca_idx'),
        ),
    ]
