# Generated by Django 5.2.5 on 2025-08-24 15:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('storefront_view', 'Storefront View'), ('purchase', 'Purchase'), ('signup', 'User Signup'), ('login', 'User Login'), ('download', 'File Download'), ('subscription_start', 'Subscription Start'), ('subscription_cancel', 'Subscription Cancel'), ('revenue', 'Revenue'), ('commission', 'Commission'), ('refund', 'Refund'), ('affiliate_click', 'Affiliate Click'), ('email_open', 'Email Open'), ('email_click', 'Email Click')], max_length=30, verbose_name='metric type')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='metric value')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('details', models.JSONField(default=dict, help_text='JSON object containing additional metric data', verbose_name='additional details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Log',
                'verbose_name_plural': 'Analytics Logs',
                'db_table': 'analytics_logs',
                'indexes': [models.Index(fields=['user', 'metric_type', 'timestamp'], name='analytics_l_user_id_22a943_idx'), models.Index(fields=['metric_type', 'timestamp'], name='analytics_l_metric__a6a608_idx'), models.Index(fields=['timestamp'], name='analytics_l_timesta_f6656b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors', models.PositiveIntegerField(default=0, verbose_name='unique visitors')),
                ('product_views', models.PositiveIntegerField(default=0, verbose_name='product views')),
                ('add_to_cart', models.PositiveIntegerField(default=0, verbose_name='add to cart')),
                ('checkout_started', models.PositiveIntegerField(default=0, verbose_name='checkout started')),
                ('purchases', models.PositiveIntegerField(default=0, verbose_name='completed purchases')),
                ('view_to_cart_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='view to cart rate')),
                ('cart_to_checkout_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='cart to checkout rate')),
                ('checkout_to_purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='checkout to purchase rate')),
                ('overall_conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='overall conversion rate')),
                ('date', models.DateField(verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_funnels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Funnel',
                'verbose_name_plural': 'Conversion Funnels',
                'db_table': 'conversion_funnels',
                'indexes': [models.Index(fields=['user', 'date'], name='conversion__user_id_e790e0_idx'), models.Index(fields=['date'], name='conversion__date_c81082_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total revenue')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monthly revenue')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='daily revenue')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='total sales')),
                ('monthly_sales', models.PositiveIntegerField(default=0, verbose_name='monthly sales')),
                ('daily_sales', models.PositiveIntegerField(default=0, verbose_name='daily sales')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='total views')),
                ('monthly_views', models.PositiveIntegerField(default=0, verbose_name='monthly views')),
                ('daily_views', models.PositiveIntegerField(default=0, verbose_name='daily views')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conversion rate percentage', max_digits=5, verbose_name='conversion rate')),
                ('active_subscribers', models.PositiveIntegerField(default=0, verbose_name='active subscribers')),
                ('churn_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly churn rate percentage', max_digits=5, verbose_name='churn rate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('calculation_date', models.DateField(auto_now_add=True, verbose_name='calculation date')),
                ('top_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_performer_metrics', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
                'db_table': 'dashboard_metrics',
                'indexes': [models.Index(fields=['user', 'calculation_date'], name='dashboard_m_user_id_a4d1b6_idx'), models.Index(fields=['updated_at'], name='dashboard_m_updated_880645_idx')],
                'unique_together': {('user', 'calculation_date')},
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='gross revenue')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='platform fee')),
                ('payment_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='payment processing fee')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT amount')),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='net revenue')),
                ('currency', models.CharField(default='ZAR', max_length=3, verbose_name='currency')),
                ('fee_type', models.CharField(choices=[('direct_sales', 'Direct Sales'), ('marketplace_sales', 'Marketplace Sales')], max_length=20, verbose_name='fee type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Analytics',
                'verbose_name_plural': 'Revenue Analytics',
                'db_table': 'revenue_analytics',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='revenue_ana_user_id_cfc3ff_idx'), models.Index(fields=['product', 'timestamp'], name='revenue_ana_product_c1029b_idx'), models.Index(fields=['fee_type'], name='revenue_ana_fee_typ_fb56c3_idx'), models.Index(fields=['timestamp'], name='revenue_ana_timesta_7620eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('search', 'Search Engine'), ('social', 'Social Media'), ('email', 'Email'), ('referral', 'Referral'), ('affiliate', 'Affiliate'), ('advertisement', 'Advertisement'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='traffic source')),
                ('medium', models.CharField(blank=True, help_text='Traffic medium (e.g., organic, cpc, social)', max_length=50, verbose_name='traffic medium')),
                ('campaign', models.CharField(blank=True, help_text='Marketing campaign name', max_length=100, verbose_name='campaign name')),
                ('referrer_url', models.URLField(blank=True, help_text='URL of the referring site', verbose_name='referrer URL')),
                ('landing_page', models.CharField(help_text='First page visited by the user', max_length=255, verbose_name='landing page')),
                ('session_duration', models.PositiveIntegerField(default=0, help_text='Session duration in seconds', verbose_name='session duration')),
                ('pages_visited', models.PositiveIntegerField(default=1, help_text='Number of pages visited in this session', verbose_name='pages visited')),
                ('converted', models.BooleanField(default=False, help_text='Whether this session resulted in a conversion (purchase)', verbose_name='converted')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traffic Analytics',
                'verbose_name_plural': 'Traffic Analytics',
                'db_table': 'traffic_analytics',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='traffic_ana_user_id_96564f_idx'), models.Index(fields=['source', 'medium'], name='traffic_ana_source_ad8a32_idx'), models.Index(fields=['converted'], name='traffic_ana_convert_a1eeca_idx'), models.Index(fields=['timestamp'], name='traffic_ana_timesta_39b022_idx')],
            },
        ),
    ]
