# Generated by Django 5.2.5 on 2025-08-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='store_banner',
            field=models.CharField(blank=True, help_text='Store banner URL', max_length=200, null=True, verbose_name='store banner'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='store_logo',
            field=models.CharField(blank=True, help_text='Store logo URL', max_length=200, null=True, verbose_name='store logo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, help_text='Profile picture URL', max_length=200, null=True, verbose_name='avatar'),
        ),
    ]
