# Generated by Django 5.2.5 on 2025-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem_cart_orders_cart_user_id_7d3dad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='download count'),
        ),
    ]
