# Generated by Django 5.2.5 on 2025-08-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldownload',
            name='file_size_mb',
            field=models.FloatField(default=0.0, verbose_name='file size (MB)'),
        ),
    ]
