# Generated by Django 5.2.5 on 2025-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_digitaldownload_file_size_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital_download', 'Digital Download'), ('course', 'Course'), ('membership', 'Membership'), ('event', 'Event'), ('community', 'Community')], default='digital_download', max_length=20, verbose_name='product type'),
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility'),
        ),
    ]
